# Generated by Django 4.1 on 2022-09-26 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Genero",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome_genero", models.CharField(max_length=45)),
            ],
            options={
                "verbose_name_plural": "Gêneros",
            },
        ),
        migrations.CreateModel(
            name="Plataforma",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("plataforma", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Usuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=45)),
                ("email", models.EmailField(max_length=254)),
                ("senha", models.CharField(max_length=15)),
                ("dt_nasc", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="Filmes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=90)),
                ("descricao", models.CharField(max_length=500)),
                ("ano_lancamento", models.DateField()),
                ("duracao", models.DurationField()),
                ("produtor", models.CharField(max_length=45)),
                ("classificacao", models.CharField(max_length=45)),
                (
                    "nome_genero",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="Filmes",
                        to="core.genero",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Artistas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=50)),
                ("descricao", models.CharField(max_length=1500)),
                (
                    "titulo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="Artistas",
                        to="core.filmes",
                    ),
                ),
            ],
        ),
    ]
