# Generated by Django 4.1 on 2022-08-25 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Filmes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=90)),
                ("descricao", models.CharField(max_length=500)),
                ("ano_lancamento", models.DateField()),
                ("duracao", models.IntegerField()),
                ("produtor", models.CharField(max_length=45)),
                ("classificacao", models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name="Genero",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome_genero", models.CharField(max_length=45)),
            ],
        ),
    ]
