# Generated by Django 4.1 on 2022-09-26 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="artistas",
            name="titulo",
        ),
    ]
