# Generated by Django 4.1.1 on 2022-09-28 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='critica',
            name='nota',
            field=models.PositiveIntegerField(choices=[(1, '1 estrelas'), (2, '2 estrelas'), (3, '3 estrelas'), (4, '4 estrelas'), (5, '5 estrelas')]),
        ),
    ]
