# Generated by Django 4.1 on 2022-08-25 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="filmes",
            name="duracao",
            field=models.DurationField(),
        ),
    ]
