# Generated by Django 4.1.1 on 2022-09-28 18:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Critica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo', models.CharField(max_length=125)),
                ('dt_critica', models.DateField()),
                ('crt_filme', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='criticas', to='core.filmes')),
                ('crt_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='criticas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
