# Generated by Django 4.1.1 on 2022-10-03 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_critica_nota'),
    ]

    operations = [
        migrations.CreateModel(
            name='Elenco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personagem', models.CharField(max_length=50)),
                ('nome', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Elenco', to='core.artistas')),
                ('titulo', models.ManyToManyField(related_name='Elenco', to='core.filmes')),
            ],
        ),
    ]
