# Generated by Django 4.1 on 2022-09-08 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_artistas"),
    ]

    operations = [
        migrations.CreateModel(
            name="Plataforma",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("plataforma", models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterModelOptions(
            name="genero",
            options={"verbose_name_plural": "Gêneros"},
        ),
    ]
